language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli; chmod u+x scripts/deploy-to-gh-pages.sh; grunt
script: ./scripts/deploy-to-gh-pages.sh
env:
  global:
  - GH_REF: github.com/ractivejs/ractive-events-hover.git
  - secure: HSXUluBG0XlD5LrNkDOvcekTvIOTc7yScw7Qy/OUlQAHQ/4Lv+LmrAQGKlwGLq1EEH58JQ1oj33z7Q09rz8cWmkIy1eEEPblQcdA987zrYCWYi92aVheMBGv7klsJc4iWvMQBZNRSwYdmtGJaSFTSQgMTbqiBJ6gV74Xi9ppfaQ=
branches:
  only:
    - master
